services:
  - type: web
    name: dog-food-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000

  - type: worker
    name: dog-food-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.tasks.scraping_tasks.celery_app worker --loglevel=info

  - type: worker
    name: dog-food-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.tasks.scraping_tasks.celery_app beat --loglevel=info